# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-27 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=200)),
                ('completed', models.BooleanField(default=False, max_length=200)),
                ('date', models.DateField(default=b'2018-07-27')),
            ],
        ),
    ]
